### PR TITLE
(WIP: NEEDED?) Merge remnants of gpucpp_june24 and gpucpp_wrap into gpucpp

### PR DESCRIPTION
**Pull request by valassi**
Hi @oliviermattelaer this is a MR into gpucpp_june24 of nb_warp_used (and possibly more) fixes.

The nb_warp_used fixes are described here https://github.com/madgraph5/madgraph4gpu/issues/885#issuecomment-2233827188

NB: as discussed in https://github.com/madgraph5/madgraph4gpu/issues/886, gpucpp_june24, with or without my changes, does NOT work for me with master_june24 (my modified version, but I am pretty sure that the problem was pre-existing).

What I am using now in my work on master_june24 (https://github.com/madgraph5/madgraph4gpu/pull/882) is my branch https://github.com/valassi/mg5amcnlo/tree/valassi_gpucpp_june24. This PR I am opening here is essentially a merge of that branch into gpucpp_june24 (the name is different, so I continue work on my side).

Here I am just filing this already so that you review my changes. And I would not know where else to merge it to, as there is no branch used for master_june24... I will probably also open it as a MR on gpucpp directly.

Can you have a look please?
Thanks
Andrea

### CODE REVIEW

**Comment by oliviermattelaer** [comment]
Here I'm confused about this PR, as stated in one of the associated isssue,
I do not see how you can have benefit with those changes. 
I do understand that such changes is important for the test, but I do not understand how you plan/want the user to specify "VECSIZE_USED". And similarly how you change "VECSIZE_USED" if you do not recompile the fortran code.

So do you expect me to change something else to change the run_card/fortran behavior? or do I miss some hack (via a patch I guess)?

Olivier

**Comment by oliviermattelaer** [comment]
Just for information, I'm going to work on this now (if you want to object -> skype please) to see the status of 
nb_warp_used and see if I can keep such change but make it interesting for when user is changing the value from the run_card. So I will likely directly push in this branch (again ping me on skype if you prefer that I work in a different branch/...)

**Comment by valassi** [comment]
Hi @oliviermattelaer, now it's me who's confused, sorry about that.

I do not remember why at some point I had two branches
- ghav_gpucpp_june24 (older, this branch)
- valassi_gpucpp_june24 (more recent, which has now been merged into gpucpp in #121 

After merging 121 into gpucpp, I have now
- merged back gpucpp into this  ghav_gpucpp_june24
- changed the base of this PR 120 to be gpucpp and not gpucpp_june24 (WE SHOULD NOT EVER USE GPUCPP_JUNE24 ANYMORE)

The bottomline is:
- there are only a few commits left here, they are all your commits from various branches, I dod not need them and have not tested them
- I imagine that they are there anyway in goodhel or 360 or both
- but if you recognise them and think that they are useful/needed, let me know, I can add this to my todo list (against gpyucppu/master, NOT against some other branch)

Lets try to converge asap to use only gpucpp and master and forget anything else please...

**Comment by oliviermattelaer** [comment]
The change in dsample.f is to my point of view important. But I checked and yes this is part of gpucpp_for360.t 
It is uncontroversial and can be merged without any thinking about it.
(it cover the case without vectorization/cuda and ensure that variable are defined in that case)


The rest is nothing crucial, either it is in 360 or ... not.

So let close this and let not care about it.

**Pull request closed without merging**
