### PR TITLE
fix(backport): Use ninja GitHub as Bitbucket repo 404s

### PR DESCRIPTION
**Pull request by matthewfeickert**
Backport of PR #154 to get Issue #153 resolved on `v3.5.x` patch releases.

* https://bitbucket.org/peraro/ninja/ no longer exists and now 404s, so migrate to using https://github.com/peraro/ninja and use a fixed commit for stability to avoid vendoring unversioned code.
   - c.f. https://github.com/peraro/ninja/commit/344f2379fd22d7e44ae14c02eb225f98b38d7b12

### CODE REVIEW

**Comment by oliviermattelaer** [comment]
Hi Matthew, 

Thanks for those patch, I have actually fixed the associated issue within 2.9.22:
https://github.com/mg5amcnlo/mg5amcnlo/commit/01d3a7d94f535fd5f9b7c923b3ff69476e268614

One big difference here is that the link for ninja (and collier) are now directly given by the HEPToolsInstaller such that the offline installer are automatically consistent between themself (and with the latest release of that repo).

Obviously for your conda port, you likely do not want to use any of those tarballs since you want to build those libraries externally to MG5aMC otherwise you might get issue with reproducibility.

PS: (from 2.9.22 it will naturally propagate to be included in 3.5.7 and  in 3.6.1 release)

**Comment by matthewfeickert** [comment]
Thanks @oliviermattelaer 

> PS: (from 2.9.22 it will naturally propagate to be included in 3.5.7 and in 3.6.1 release)

Can you explain a bit more about how this works and which branches you make releases from? This is confusing to me as https://github.com/mg5amcnlo/mg5amcnlo/commit/01d3a7d94f535fd5f9b7c923b3ff69476e268614 exists only on branch [`2.9.22`](https://github.com/mg5amcnlo/mg5amcnlo/tree/2.9.22) and not in [`3.5.6`](https://github.com/mg5amcnlo/mg5amcnlo/tree/3.5.6) (which this PR targets), [`3.6.1`](https://github.com/mg5amcnlo/mg5amcnlo/tree/3.6.1) (PR https://github.com/mg5amcnlo/mg5amcnlo/pull/154), or on the default branch [`3.x`](https://github.com/mg5amcnlo/mg5amcnlo/tree/3.x). So this is still broken for anyone trying to work off of those branches, and I would not think to look at a branch that corresponds to a release that is not longer the current LTS.

From the README on the default branch

https://github.com/mg5amcnlo/mg5amcnlo/blob/55a291dc8def762938a964cc1343c6d76af5b843/README.md?plain=1#L69-L75

[`v3.5.6` is the latest LTS](https://launchpad.net/mg5amcnlo/lts/lts.3.5.x)

image

which is why I targeted the [`3.5.6`](https://github.com/mg5amcnlo/mg5amcnlo/tree/3.5.6) branch. But it seems I should have targeted branch [`2.9.22`](https://github.com/mg5amcnlo/mg5amcnlo/tree/2.9.22) instead?

I also don't understand the relationship between the [`3.x`](https://github.com/mg5amcnlo/mg5amcnlo/tree/3.x) branch and the [`3.6.1`](https://github.com/mg5amcnlo/mg5amcnlo/tree/3.6.1) branch as you have [`3.x`](https://github.com/mg5amcnlo/mg5amcnlo/tree/3.x) as the default, yet [`3.6.1`](https://github.com/mg5amcnlo/mg5amcnlo/tree/3.6.1) is the one that is **ahead** https://github.com/mg5amcnlo/mg5amcnlo/compare/3.x...3.6.1

**Comment by oliviermattelaer** [comment]
2.9.x is still under support (and new release) in december 2025.
So we still have a full year of support in front of us for 2.9.x with therefore plenty of time for 3.5.x to gain in stability as well.

Our way to use the branch tries to mimick the way branch were used in launchpad (which was much more clean than the one in git)

So 3.x is the branch that jump from public release to public release. If you want to use git directly but stay at public release level this is the branch for you.
This is also the branch on which many CI are related since a commit in this branch means a new release.

Currently 3.x contains the last commit from 3.6.0
and therefore yes, 3.6.1 is ahead.

The same is true for LTS that is jumping from releases to releases and which is in currently in sync with 2.9.21

For LTS 3.5, we will probably need a new branch for that, but this is not yet in place.

Maybe it would make more sense to put our default branch on our LTS branch or change it as each release of the LTS?
Not sure what is the clearest/best

Cheers,

Olivier


On 30 Oct 2024, at 00:18, Matthew Feickert ***@***.***> wrote:



Thanks @oliviermattelaer<https://github.com/oliviermattelaer>

PS: (from 2.9.22 it will naturally propagate to be included in 3.5.7 and in 3.6.1 release)

Can you explain a bit more about how this works and which branches you make releases from? This is confusing to me as 01d3a7d<https://github.com/mg5amcnlo/mg5amcnlo/commit/01d3a7d94f535fd5f9b7c923b3ff69476e268614> exists only on branch 2.9.22<https://github.com/mg5amcnlo/mg5amcnlo/tree/2.9.22> and not in 3.5.6<https://github.com/mg5amcnlo/mg5amcnlo/tree/3.5.6> (which this PR targets), 3.6.1<https://github.com/mg5amcnlo/mg5amcnlo/tree/3.6.1> (PR #154<https://github.com/mg5amcnlo/mg5amcnlo/pull/154>), or on the default branch 3.x<https://github.com/mg5amcnlo/mg5amcnlo/tree/3.x>. So this is still broken for anyone trying to work off of those branches, and I would not think to look at a branch that corresponds to a release that is not longer the current LTS.

From the README on the default branch

https://github.com/mg5amcnlo/mg5amcnlo/blob/55a291dc8def762938a964cc1343c6d76af5b843/README.md?plain=1#L69-L75

v3.5.6 is the latest LTS<https://launchpad.net/mg5amcnlo/lts/lts.3.5.x>

image.png (view on web)<https://github.com/user-attachments/assets/d46895b0-a3b3-4a48-b2dc-17b4aea3b43b>

which is why I targeted the 3.5.6<https://github.com/mg5amcnlo/mg5amcnlo/tree/3.5.6> branch. But it seems I should have targeted branch 2.9.22<https://github.com/mg5amcnlo/mg5amcnlo/tree/2.9.22> instead?

I also don't understand the relationship between the 3.x<https://github.com/mg5amcnlo/mg5amcnlo/tree/3.x> branch and the 3.6.1<https://github.com/mg5amcnlo/mg5amcnlo/tree/3.6.1> branch as you have 3.x<https://github.com/mg5amcnlo/mg5amcnlo/tree/3.x> as the default, yet 3.6.1<https://github.com/mg5amcnlo/mg5amcnlo/tree/3.6.1> is the one that is ahead 3.x...3.6.1<https://github.com/mg5amcnlo/mg5amcnlo/compare/3.x...3.6.1>

**Comment by matthewfeickert** [comment]
Thanks for explaining this @oliviermattelaer. :+1: It helps, though I have some more clarifying questions, but I perhaps the biggest one that I don't understand can be summarized as "If I there is a bug that exists across multiple branches and so would affect multiple future patch releases what is the recommended way to open up PRs to fix it?"

> So we still have a full year of support in front of us for 2.9.x with therefore plenty of time for 3.5.x to gain in stability as well

I don't think I understand what you mean by "gain in stability as well". Is the `3.5.x` series not viewed as production ready now?

> So 3.x is the branch that jump from public release to public release. If you want to use git directly but stay at public release level this is the branch for you.
> ...
> Currently 3.x contains the last commit from 3.6.0 and therefore yes, 3.6.1 is ahead.

Okay, so [3.x](https://github.com/mg5amcnlo/mg5amcnlo/tree/3.x) is viewed as the public release branch and so commits to it are only from merges swept in from other branches that are ahead or from backports (correct?)? What is viewed as the active development branch? [`3.6.1`](https://github.com/mg5amcnlo/mg5amcnlo/tree/3.6.1)?

> Maybe it would make more sense to put our default branch on our LTS branch or change it as each release of the LTS? Not sure what is the clearest/best.

I think it depends a lot on how you want to outwardly communicate to people what the workflow for the GitHub repository is RE: use and development.

Most open source projects have the default branch be their `main` branch which is where the head of active development is (e.g. [Awkward](https://github.com/scikit-hep/awkward), [SciPy](https://github.com/scipy/scipy), [Julia](https://github.com/JuliaLang/julia), [Go](https://github.com/golang/go)). The assumption is that if people are coming to the repository they want the active code to be able to test or contribute to, and if they want a release they get it from a release tag in the repository, and if they want to contribute a bug fix they first make a PR to fix the bug in the `main` branch (development) and then make a follow up PR to backport that fix to the relevant patch release branch (e.g. the latest `matplotlib` release at the time of me writing is [`v3.9.2`](https://github.com/matplotlib/matplotlib/releases/tag/v3.9.2) and any further patch releases in the `v3.9.x` series are made from the [`v3.9.x`](https://github.com/matplotlib/matplotlib/tree/v3.9.x) branch).

While this isn't the system that you've chosen (which is fine), I think it actually maps onto how you are viewing people getting and using the `mg5amcnlo` code. From https://github.com/mg5amcnlo/mg5amcnlo/issues/10#issuecomment-2442805732, you're not expecting that people who want to get a release are getting it from GitHub, but rather downloading a distribution from Launchpad.

If you are thinking of the GitHub repository as not being a source of the development but an archival system of public releases [like PYTHIA8 does with their GitLab repository](https://gitlab.com/Pythia8/releases) then I think it makes sense to have the latest public release be the default branch. Though using the naming convention of `3.x` for this is confusing as the `x` convention is used broadly in open source to indicate that `1.2.x` means "this is the actively maintained patch release branch for the next patch release in the `v1.2` API series". You're communicating something similar but still different, which I believe is `3.x` means "the latest `3.x{.y}` public release was made from this branch but it is not actively developed and viewed as static until the next `3.x{.y}` release".

**Comment by oliviermattelaer** [comment]
"If I there is a bug that exists across multiple branches and so would affect multiple future patch releases what is the recommended way to open up PRs to fix it?"

I would say that it does not really matter, since I will take the PR and potentially cherry-pick the patch to the branch  that I want.

But the rule is that if the bug impact a LTS then it should target the branch which is develloping the next release for that LTS.
If they are more than one LTS impacted then you should target the oldest one of those release.
If no LTS are affected then you should use the branch develloping the next release.

Now if this is not a bug fix but a new feature then it can not target LTS branch and only the active development branch (so currently 3.6.1) can be targetted
(again I will fix that issue in case of PR targetting the wrong branch)


Okay, so 3.x<https://github.com/mg5amcnlo/mg5amcnlo/tree/3.x> is viewed as the public release branch and so commits to it are only from merges swept in from other branches that are ahead or from backports (correct?)? What is viewed as the active development branch? 3.6.1<https://github.com/mg5amcnlo/mg5amcnlo/tree/3.6.1>?

3.x will only be updated ONLY via a merge of 3.6.1 (or 3.7.0 which will then include the branch 3.6.1).

In details the operation of merging 3.6.1 into 3.x are the following ones:
-  we will have merge 2.9.22 in LTS, (i.e release of 2.9.22)
-  have merged 2.9.22 within 3.5.7,
-  merged the "new" 3.5.7 in "LTS_3.5" (which does not exists yet), (i.e release of 3.7.7)
-  then merge this new "LTS_35" into this 3.6.1.
-  then merge 3.6.1 into 3.x (i.e. make the official release of 3.6.1)

(Obviously we can release of version of a LTS without doing the equivalent for the latest development one if needed)


I don't think I understand what you mean by "gain in stability as well".

The current LTS version of 2.9.x had been more than 16 releases (~4 years) of the code with quite strict "bug fixing" only release.
The rate at which bug are discover for that release and their importance is actually quite low.
Since this was our first LTS, I can say that is the more stable/thrustable release ever.

It is clear to me that 3.5.6 is not yet at such level of stability and still has to pass the CMS physics validation step.
So yes it is ready for production but yes it has certainly more bugs than 2.9.x (but it has many new features than 2.9.x is not able to do).
So my hope is that in a year from now, I could have a close enough level of quality for 3.5.x release.


If you are thinking of the GitHub repository as not being a source of the development but an archival system of public releases like PYTHIA8 does with their GitLab repository<https://gitlab.com/Pythia8/releases> then I think it makes sense to have the latest public release be the default branch. Though using the naming convention of 3.x for this is confusing as the x convention is used broadly in open source to indicate that 1.2.x means "this is the actively maintained patch release branch for the next patch release in the v1.2 API series". You're communicating something similar but still different, which I believe is 3.x means "the latest 3.x{.y} public release was made from this branch but it is not actively developed and viewed as static until the next 3.x{.y} release".

What name would you suggest then?


Cheers,

Olivier


On 30 Oct 2024, at 20:49, Matthew Feickert ***@***.***> wrote:



Thanks for explaining this @oliviermattelaer<https://github.com/oliviermattelaer>. 👍 It helps, though I have some more clarifying questions, but I perhaps the biggest one that I don't understand can be summarized as "If I there is a bug that exists across multiple branches and so would affect multiple future patch releases what is the recommended way to open up PRs to fix it?"

So we still have a full year of support in front of us for 2.9.x with therefore plenty of time for 3.5.x to gain in stability as well

I don't think I understand what you mean by "gain in stability as well". Is the 3.5.x series not viewed as production ready now?

So 3.x is the branch that jump from public release to public release. If you want to use git directly but stay at public release level this is the branch for you.
...
Currently 3.x contains the last commit from 3.6.0 and therefore yes, 3.6.1 is ahead.

Okay, so 3.x<https://github.com/mg5amcnlo/mg5amcnlo/tree/3.x> is viewed as the public release branch and so commits to it are only from merges swept in from other branches that are ahead or from backports (correct?)? What is viewed as the active development branch? 3.6.1<https://github.com/mg5amcnlo/mg5amcnlo/tree/3.6.1>?

Maybe it would make more sense to put our default branch on our LTS branch or change it as each release of the LTS? Not sure what is the clearest/best.

I think it depends a lot on how you want to outwardly communicate to people what the workflow for the GitHub repository is RE: use and development.

Most open source projects have the default branch be their main branch which is where the head of active development is (e.g. Awkward<https://github.com/scikit-hep/awkward>, SciPy<https://github.com/scipy/scipy>, Julia<https://github.com/JuliaLang/julia>, Go<https://github.com/golang/go>). The assumption is that if people are coming to the repository they want the active code to be able to test or contribute to, and if they want a release they get it from a release tag in the repository, and if they want to contribute a bug fix they first make a PR to fix the bug in the main branch (development) and then make a follow up PR to backport that fix to the relevant patch release branch (e.g. the latest matplotlib release at the time of me writing is v3.9.2<https://github.com/matplotlib/matplotlib/releases/tag/v3.9.2> and any further patch releases in the v3.9.x series are made from the v3.9.x<https://github.com/matplotlib/matplotlib/tree/v3.9.x> branch).

While this isn't the system that you've chosen (which is fine), I think it actually maps onto how you are viewing people getting and using the mg5amcnlo code. From #10 (comment)<https://github.com/mg5amcnlo/mg5amcnlo/issues/10#issuecomment-2442805732>, you're not expecting that people who want to get a release are getting it from GitHub, but rather downloading a distribution from Launchpad.

If you are thinking of the GitHub repository as not being a source of the development but an archival system of public releases like PYTHIA8 does with their GitLab repository<https://gitlab.com/Pythia8/releases> then I think it makes sense to have the latest public release be the default branch. Though using the naming convention of 3.x for this is confusing as the x convention is used broadly in open source to indicate that 1.2.x means "this is the actively maintained patch release branch for the next patch release in the v1.2 API series". You're communicating something similar but still different, which I believe is 3.x means "the latest 3.x{.y} public release was made from this branch but it is not actively developed and viewed as static until the next 3.x{.y} release".

**Comment by matthewfeickert** [comment]
> But the rule is that if the bug impact a LTS then it should target the branch which is develloping the next release for that LTS.
> If they are more than one LTS impacted then you should target the oldest one of those release.
> If no LTS are affected then you should use the branch develloping the next release.
> 
> Now if this is not a bug fix but a new feature then it can not target LTS branch and only the active development branch (so currently 3.6.1) can be targetted
(again I will fix that issue in case of PR targetting the wrong branch)

Thanks @oliviermattelaer. This is a helpful overview. :+1: 

> The current LTS version of 2.9.x had been more than 16 releases (~4 years) of the code with quite strict "bug fixing" only release.
The rate at which bug are discover for that release and their importance is actually quite low.
Since this was our first LTS, I can say that is the more stable/thrustable release ever.
> 
> It is clear to me that 3.5.6 is not yet at such level of stability and still has to pass the CMS physics validation step.
So yes it is ready for production but yes it has certainly more bugs than 2.9.x (but it has many new features than 2.9.x is not able to do).
So my hope is that in a year from now, I could have a close enough level of quality for 3.5.x release.

Thanks. This is also useful to understand how things are viewed.

> What name would you suggest then?

If the goal is to indicate that the default branch is **not** the active development branch (aka, don't make PRs against this branch), I would either name it something explicit like "release" or "public-release". I'm assuming that all Git tags of public releases are also made from this branch then and so by selecting a tag with Git (e.g. `git checkout v3.5.6`) you would just be traversing back through the history of the branch.

The bit of nuance here is conveying this information in the README as GitHub assumes that the default branch is actively developed and so by default a PR to any repository targets the default branch. This just requires people to read, but the more explicit you can make things the less mistargeted PRs you'll get.

**Pull request closed without merging**
