### PR TITLE
Fixed typo in UFO parser for cpp output

### PR DESCRIPTION
**Pull request by zeniheisser**
Fixed small bug where non-standard UFO models could not be exported using cpp output (simple typo)

### CODE REVIEW

**Comment by zeniheisser** [comment]
Tagging @valassi. Small typo in the UFO parser means output to cpp generally will crash after switching model.

**Comment by valassi** [comment]
Hi @zeniheisser thanks. Can you transform this into a PR against the gpucpp branch please? (@oliviermattelaer do you agree? I think it is better than main, so we can directly use it in our GPU developpments)

**Comment by zeniheisser** [comment]
@valassi I think it fits here, since it is an upstream bug, but we certainly should fix it in the gpucpp branch as well

**Comment by valassi** [comment]
Thanks again Zenny. I committed this to gpucpp (I wanted to make a MR but I made a mistake, anyway it is a really minor fix)
https://github.com/mg5amcnlo/mg5amcnlo/commit/8512c16a49dc96adb21505b9359ba811b0d169ca

**Comment by oliviermattelaer** [comment]
Merged in https://github.com/mg5amcnlo/mg5amcnlo/commit/550172de74a297af7d175bf8a3c458c170b0792d
(in LTS_dev)

**Pull request closed without merging**
