### PR TITLE
Fix moved cern amcatnlo webpage

### PR DESCRIPTION
**Pull request by APN-Pucky**
I have not looked for more cern.ch pages that might also need a changed URL.

### CODE REVIEW

**Comment by oliviermattelaer** [comment]
Thanks for the notification, I will ask the website responsible if this is a temporary change or not and then see what is the correct action to perform.

Cheers,

Olivier

**Comment by APN-Pucky** [comment]
Thanks, any update? As of now both sides are unavailable...

**Comment by oliviermattelaer** [comment]
Information last month was that yes we had to update the link, but looks like the cern transition out of afs is creating additional issue. I did send an email to the website responsible, and they will likely opening a ticket to cern IT to see what the status is.

Thanks for the notification,

Olivier

**Comment by oliviermattelaer** [comment]
The website https://amcatnlo.web.cern.ch/amcatnlo/
and https://amcatnlo.web.cern.ch
are now both responding (and both point to the same content)

Thanks,

Olivier

**Pull request closed without merging**
