### PR TITLE
Customize repository

### PR DESCRIPTION
**Pull request by Bruno-M-S-Oliveira**
I have created a pull request including several changes aimed at improving compatibility with the (settings and features customization)[https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository] for MadGraph5_aMC@NLO.

One of the key focuses of this pull request was to ensure that essential information from both https://launchpad.net/mg5amcnlo and https://server06.fynu.ucl.ac.be/projects/madgraph/wiki was included in the README.

While I attempted to move the citations to a CITATION.cff file, I discovered that the format is only appropriate for a single reference and therefore left them in the README.

Moreover, as suggested by issue #42, I agree that the CONTRIBUTING.md file still requires a lot of rewriting to fulfill its purpose as an introduction on how to contribute. As a reference for structuring and formatting the file correctly, I suggested using the [GitHub Docs contribution guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

I invite you to review my changes and provide any feedback or concerns you may have. Thank you for your time and consideration.

### CODE REVIEW

**Comment by oliviermattelaer** [comment]
I guess, you choose the wrong targetting branch right?
I guess that you want to include this for the 3.5.1 releases (or in a way better the 3.6.0 release but I do not think that we have created a branch for that future release yet)

**Comment by Bruno-M-S-Oliveira** [comment]
> I guess, you choose the wrong targetting branch right? I guess that you want to include this for the 3.5.1 releases (or in a way better the 3.6.0 release but I do not think that we have created a branch for that future release yet)

Seems like it yes, I've since rebased my changes into 3.5.1 so you should be able to merge it into that branch.

**Comment by Bruno-M-S-Oliveira** [comment]
Would you be interested in merging this?
If yes, I can address the conflicts with the current release.
Otherwise, you can close this PR.

**Comment by oliviermattelaer** [comment]
I have taken your readme, change it a bit and pushed in the 3.6.0 branch.

Thanks for the formating and the usefull change. With that included now, i guess we can close this PR.
Thanks,

Olivier

**Comment by Bruno-M-S-Oliveira** [comment]
I'm happy my proposal was of use.

I would also suggest moving the `AUTHORS` and `LICENSE` files from `madgraph/` to the root directory. Not only is this more standard, but the latter change would allow the "License" toggle in the GitHub interface to display the license itself rather than `madgraph/LICENSE`.

Bruno

**Pull request closed without merging**
