### PR TITLE
Lo vect diagid

### PR DESCRIPTION
**Pull request by oliviermattelaer**
Hi Andrea,

You can merge this branch as soon as you are ready for it.
This branch include change to the amp2 numbering as we discussed before.

For completeness, the main goal was to be able to have the same index for the identification of the amp2 index as for the one related to the definition of the allowed color flow for the event.

I will still improve this branch to be sure/upgrade other mode to have consistent code and/or be sure that everything is fine (like loop-induced/....) but this can be done independently within this branch or to the other ones when this is merged.

### CODE REVIEW

**Comment by oliviermattelaer** [comment]
For more details on the change/ list of validation/... 
See https://github.com/oliviermattelaer/mg5amc_test/issues/19
Note those validations leads to discovering a bug in the official version: 
https://github.com/mg5amcnlo/mg5amcnlo/issues/6

**Comment by valassi** [comment]
Hi Olivier, no sorry I had forgotten about this one.

For the moment I am basing myself on vecMLM. Or more precisely I created gpucpp which is now an as-is copy of vecMLM, and I created MR #23 and #24 against that.

I can put this in the pipeline. Maybe the easiest for me however is to do #23 and #24 first, because all my madgraph4gpu work is based essentially on vecMLM+23+24.

Is that OK?

**Comment by valassi** [comment]
Hi @oliviermattelaer sorry again I had forgotten about this.

This is now critical. I implemented the color choice in https://github.com/madgraph5/madgraph4gpu/pull/573, and this succeeds for a few processes and channles, but fails otherwise. I have seen that coloramps.inc in Fortran is different from the coloramps.h that I get in cudacpp based on some code in your export_cpp.

Am I correct that this lo_vect_diagid may be the missing piece?

Anyway, another problem is that you had filed this as a MR on 3.1.1_lo_vectorization, but in the meantime there are conflicts. And I am actually using vecMLM as the basis for my work.

Can you please change the target of this MR to vecMLM, and fix the conflicts? (Do this now, then my vecsize and vecsize2 will come later)

Thanks
Andrea

**Comment by oliviermattelaer** [comment]
Hi Andrea, 

I have solve the conflicts.

Cheers,

Olivier

**Comment by valassi** [comment]
Hi Olivier, thanks a lot.
Sorry, this does not build. If I take your latest commit here and generate ggtt (my "--mad --upstream" for my record), I get
```
/cvmfs/sft.cern.ch/lcg/releases/gcc/11.2.0-ad950/x86_64-centos7/bin/gfortran -w -fPIC  -ffixed-line-length-132 -w -c auto_dsig1.f -I../../Source/ -fopenmp
auto_dsig1.f:453:7:

  453 |       C.     COL_RAND: A LIST OF RANDOM NUMBER (WILL BE USED TO PICK
      |       1
Error: Unclassifiable statement at (1)
auto_dsig1.f:155:13:

  155 |       CHANNEL = SUBDIAG(1)
      |             1
Error: Symbol ‘channel’ at (1) has no IMPLICIT type
auto_dsig1.f:388:62:

  388 |       CALL SMATRIX1_MULTI(P_MULTI, HEL_RAND, COL_RAND, CHANNEL,
      |                                                              1
Error: Symbol ‘channel’ at (1) has no IMPLICIT type
make: *** [auto_dsig1.o] Error 1
```
Can you confirm or am I doing something wrong?

More generally, I am a bit confused: for the various channel variables, should we take ICONFIG or SUBDIAG(1)? These are two different commons
```
     INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
C     Keep track of whether cuts already calculated for this event
      LOGICAL CUTSDONE,CUTSPASSED
      COMMON/TO_CUTSDONE/CUTSDONE,CUTSPASSED

      INTEGER SUBDIAG(MAXSPROC),IB(2)
      COMMON/TO_SUB_DIAG/SUBDIAG,IB
```

Thanks Andrea

**Comment by valassi** [comment]
> Sorry, this does not build. If I take your latest commit here and generate ggtt (my "--mad --upstream" for my record), I get
> 
> ```
> /cvmfs/sft.cern.ch/lcg/releases/gcc/11.2.0-ad950/x86_64-centos7/bin/gfortran -w -fPIC  -ffixed-line-length-132 -w -c auto_dsig1.f -I../../Source/ -fopenmp
> auto_dsig1.f:453:7:
> 
>   453 |       C.     COL_RAND: A LIST OF RANDOM NUMBER (WILL BE USED TO PICK
>       |       1
> Error: Unclassifiable statement at (1)
> auto_dsig1.f:155:13:
> 
>   155 |       CHANNEL = SUBDIAG(1)
>       |             1
> Error: Symbol ‘channel’ at (1) has no IMPLICIT type
> auto_dsig1.f:388:62:
> 
>   388 |       CALL SMATRIX1_MULTI(P_MULTI, HEL_RAND, COL_RAND, CHANNEL,
>       |                                                              1
> Error: Symbol ‘channel’ at (1) has no IMPLICIT type
> make: *** [auto_dsig1.o] Error 1
> ```

Hi @oliviermattelaer I have added some patches in #28 to fix these build errors, can you please review them?

As mentioned there, there are other issues (the order of coloramps.h is still wrong, and in addition now the "AMP2(i)=AMP2(i)+AMP(j)*DCONJG(AMP(j))" lines change and I get a wrong cross section). But these build fixes in #28 are probabbly needed anyway

Thanks Andrea

**Comment by oliviermattelaer** [comment]
re-checking the status before the merge:
(madevent fortran number only here (no vectorization))
tt~ : 505.5 (LTS = 505.8)
tt~j: 575.3 (LTS= 574.4+- 1.4)
tt~jj:422.1  (LTS = 420.9+-1.2)
w+w-jj:  23.46046349     (LTS = 23.39 +- 0.06254 pb)
but one needs to double check qq> w+ w-qq which is super slow (and helicity recycling crashing for qq>qqw+w-)

To check the code output the LTS is returning
```
        AMP2(1)=AMP2(1)+AMP(1)*DCONJG(AMP(1))
        AMP2(2)=AMP2(2)+AMP(2)*DCONJG(AMP(2))
        AMP2(3)=AMP2(3)+AMP(3)*DCONJG(AMP(3))
c.     NO AMP(4)
        AMP2(5)=AMP2(5)+AMP(7)*DCONJG(AMP(7))
        AMP2(6)=AMP2(6)+AMP(8)*DCONJG(AMP(8))
        AMP2(7)=AMP2(7)+AMP(9)*DCONJG(AMP(9))
        AMP2(9)=AMP2(9)+AMP(13)*DCONJG(AMP(13))
        AMP2(10)=AMP2(10)+AMP(14)*DCONJG(AMP(14))
        AMP2(11)=AMP2(11)+AMP(15)*DCONJG(AMP(15))
        AMP2(13)=AMP2(13)+AMP(19)*DCONJG(AMP(19))
        AMP2(14)=AMP2(14)+AMP(20)*DCONJG(AMP(20))
        AMP2(15)=AMP2(15)+AMP(21)*DCONJG(AMP(21))
        AMP2(17)=AMP2(17)+AMP(25)*DCONJG(AMP(25))
        AMP2(18)=AMP2(18)+AMP(26)*DCONJG(AMP(26))
        AMP2(19)=AMP2(19)+AMP(27)*DCONJG(AMP(27))
```
while this branch is returning
```
        AMP2(1)=AMP2(1)+AMP(1)*DCONJG(AMP(1))
	AMP2(2)=AMP2(2)+AMP(2)*DCONJG(AMP(2))
        AMP2(3)=AMP2(3)+AMP(3)*DCONJG(AMP(3))
	AMP2(4)=AMP2(4)+AMP(7)*DCONJG(AMP(7))
        AMP2(5)=AMP2(5)+AMP(8)*DCONJG(AMP(8))
        AMP2(6)=AMP2(6)+AMP(9)*DCONJG(AMP(9))
        AMP2(7)=AMP2(7)+AMP(13)*DCONJG(AMP(13))
        AMP2(8)=AMP2(8)+AMP(14)*DCONJG(AMP(14))
        AMP2(9)=AMP2(9)+AMP(15)*DCONJG(AMP(15))
        AMP2(10)=AMP2(10)+AMP(19)*DCONJG(AMP(19))
        AMP2(11)=AMP2(11)+AMP(20)*DCONJG(AMP(20))
        AMP2(12)=AMP2(12)+AMP(21)*DCONJG(AMP(21))
        AMP2(13)=AMP2(13)+AMP(25)*DCONJG(AMP(25))
        AMP2(14)=AMP2(14)+AMP(26)*DCONJG(AMP(26))
        AMP2(15)=AMP2(15)+AMP(27)*DCONJG(AMP(27))
```

So I guess that including this branch is important to reduce memory consumption and simplifying the creation of some file. I need to dig into this branch again to fix the issue with q q > w+ w- q q and be sure that everything is under control at the fortran level and then I will redo a merge and then redo validation at fortran level only.

**Comment by oliviermattelaer** [comment]
for qq > w+w-qq
we do have 
```
        AMP2(7)=AMP2(7)+AMP(7)*DCONJG(AMP(7))
        AMP2(8)=AMP2(8)+AMP(8)*DCONJG(AMP(8))
        AMP2(9)=AMP2(9)+AMP(9)*DCONJG(AMP(9))
        AMP2(10)=AMP2(10)+AMP(10)*DCONJG(AMP(10))
        AMP2(14)=AMP2(14)+AMP(14)*DCONJG(AMP(14))
```
So we do have gap, (because we have more than one of such file) but we keep the symmetry on the index.
So now I wonder if this is a real gain (quite small one actually)

**Pull request closed without merging**
