### PR TITLE
Change to the PS restriction for electron beam

### PR DESCRIPTION
**Pull request by oliviermattelaer**
So the following script now works:
generate e+ e- > t t~
output
launch
shower=PY8
set lpp2 3
set lpp1 -3
set pdlabel cepc240ll
set bypass_check partonshower

as well as this one:
generate e+ e- > t t~
output
launch
shower=PY8
set lpp2 3
set lpp1 -3
set pdlabel isronlyll

in the last one, I do force that QED shower is on automatically (this force can also be turned off by the "bypass_check partonshower".

### CODE REVIEW

**Comment by marcozaro** [comment]
Hi Olivier,
can we make the experimentalists try the fix?
is the code publicly accessible?

Thanks

Marco

**Comment by oliviermattelaer** [comment]
Yes, this is public (as well as your last email which is public here: https://github.com/mg5amcnlo/mg5amcnlo/pull/73#issuecomment-1829348323)

The code can also be downloaded as a zip file : https://github.com/mg5amcnlo/mg5amcnlo/archive/c7d01da2631a9b3bc5b6403ba26ae2e0c08ef7fa.zip

Or can be provided via git
git clone -b ee_with_ps git@github.com:mg5amcnlo/mg5amcnlo.git
or
git clone -b ee_with_ps https://github.com/mg5amcnlo/mg5amcnlo.git
(the first command is better if they have a github account, while the second work even without a github account)

**Comment by oliviermattelaer** [comment]
@marcozaro any objection to merge this in 3.5.3?

**Comment by marcozaro** [comment]
Sorry, nothing against, go ahead
Thanks!

**Pull request merged**
